Fix access modifier for ring buffer methods
ReadFromRingBuffer and WriteToRingBuffer need to be public
for access from opm.h when using multi-channel mode.

Fixes compilation error:
- error C2248: 'Adpcm::ReadFromRingBuffer': private member